UPDATE ESTADOS
SET NOME = 'Maranhão'
WHERE SIGLA = 'MA';

SELECT ESTADOS.NOME FROM ESTADOS 
WHERE SIGLA = 'MA';

UPDATE ESTADOS EST
SET EST.NOME = "Paraná",
	POPULACAO = 11.2
WHERE SIGLA = 'PR';

SELECT NOME, SIGLA, POPULACAO FROM ESTADOS 
WHERE SIGLA = 'PR';