SELECT * FROM PREFEITOS;
SELECT * FROM CIDADES;

SELECT * FROM CIDADES C INNER JOIN PREFEITOS P ON C.ID = P.CIDADE_ID;

SELECT * FROM CIDADES C LEFT JOIN PREFEITOS P ON C.ID = P.CIDADE_ID;
-- SELECT * FROM CIDADES C LEFT OUTER JOIN PREFEITOS P ON C.ID = P.CIDADE_ID;

SELECT * FROM CIDADES C RIGHT JOIN PREFEITOS P ON C.ID = P.CIDADE_ID;


-- FULL JOIN:
SELECT * FROM CIDADES C LEFT JOIN PREFEITOS P ON C.ID = P.CIDADE_ID
UNION
SELECT * FROM CIDADES C RIGHT JOIN PREFEITOS P ON C.ID = P.CIDADE_ID;

-- FULL JOIN COM DUPLICACOES:
SELECT * FROM CIDADES C LEFT JOIN PREFEITOS P ON C.ID = P.CIDADE_ID
UNION ALL 
SELECT * FROM CIDADES C RIGHT JOIN PREFEITOS P ON C.ID = P.CIDADE_ID;