SELECT E.NOME EMPRESA, C.NOME CIDADE
FROM EMPRESAS E, EMPRESAS_UNIDADES EU, CIDADES C
WHERE E.ID = EU.EMPRESA_ID AND C.ID = EU.CIDADE_ID;

SELECT E.NOME AS EMPRESA, C.NOME AS CIDADE
FROM EMPRESAS E, EMPRESAS_UNIDADES EU, CIDADES C
WHERE E.ID = EU.EMPRESA_ID AND C.ID = EU.CIDADE_ID
AND SEDE;