CREATE TABLE IF NOT EXISTS PREFEITOS(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
	nome VARCHAR(255) NOT NULL,
	cidade_id INT UNSIGNED,
	PRIMARY KEY (id),
	UNIQUE KEY (cidade_id),
	FOREIGN KEY(cidade_id) REFERENCES CIDADES (id)
);